exp_name: my_experiment
description: ''
model: qwen/qwen3-vl-30b-a3b-instruct
prompt_id: cv_enhanced_p4
max_size:
- 768
- 768
quality: 80
segmentor_weights: /root/otto/XiaoanNew/assets/weights/best.pt
segmentor_device: cuda:0
conf_threshold: 0.6
data_folders:
- /root/otto/XiaoanNew/data/compliance/no_val
- /root/otto/XiaoanNew/data/compliance/yes_val
output_root: /root/otto/XiaoanNew/outputs/test_outputs
save_visuals: true
max_workers: 15
timestamp: '20260325_101632'
